### ISSUE TITLE
[BUG] Teleport Error

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#445] opened 2023-03-08 23:37 UTC
User is reporting that teleporting to a tile results in this error and failure. Using coordinates does work for them. So far I can't replicate it.

Edit: User says the teleports only fail if its directly targeting a tile that has nothing in the action list. Using Tagger to teleport to a blank tile works as expected.

![image](https://user-images.githubusercontent.com/99844555/223877284-7b9dc5d7-a4d5-4964-9056-1c0364636bd9.png)

![image](https://user-images.githubusercontent.com/99844555/223877313-da20ef00-7461-485b-bbc2-a53fc0ce7236.png)

MATT 10.12
FTC

**Comment by ironmonk88** [comment] 2023-04-09 05:59
Requires the teleport destination to have `Trigger using image instead of border`

**Comment by ironmonk88** [comment] 2023-04-09 06:11
I believe this is a duplicate of #437

**Comment by ironmonk88** [comment] 2023-04-14 05:28
Should be fixed in the latest release

**Closed by ironmonk88** 2023-04-14 05:28 UTC
Labels: duplicate, fixed waiting release
