### ISSUE TITLE
[BUG] Conflict with Darkness Activated Tile

### ISSUE THREAD

**Issue by MapperD** [ironmonk88/monks-active-tiles#639] opened 2023-11-12 03:20 UTC
The "When" drop down field in the Triggers Setup tab does not work. All I have is the default Enter which works but I cannot access the other options if Darkness Activated Tile is also active

**Please complete as much of the following information as possible:**
 - Browser [Standalone Application]
 - Foundry Version [11.315]
 - System [Harnmaster 3]
 - Module version [11.12]
 - Are there any errors in the console [None I can see, however, with the console open and I attempt to open the tile settings I get a Pause on Debugger message and must press resume for the tile settings window to open ]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. [How I determined it was Darkness Activated Tile]

**Comment by Crowguard** [comment] 2023-11-13 14:38
Duplicate of #530 .

**Comment by ironmonk88** [comment] 2023-11-15 01:58
Closing because it's not an issue I can solve, the module in question is out of date, and MATT handles this itself now.

**Closed by ironmonk88** 2023-11-15 01:58 UTC
