### ISSUE TITLE
[BUG] Use Tagger

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#390] opened 2022-12-22 20:52 UTC
Some actions targeting a Tag are only targeting the oldest entity type on the scene with that Tag, in a specific order of entity types. So far the only Action I've found an error on is Alter. Tested with various attributes as well. 

Different types seem to have priority over others; if there's one type with the same tag, it will get moved even if its not the oldest amongst other types.
Tokens>Lights>Sounds>Tiles>Drawings & Notes (Don't know where these sit. Can't really run a MATT action without a tile).

## Alter
Results in the error below.

https://user-images.githubusercontent.com/99844555/209223980-b6ca9a7c-75d1-438f-b69e-5837f028d0b1.mp4

![image](https://user-images.githubusercontent.com/99844555/209222763-acd8e07b-9644-4cc9-9f25-ad1e6b254bd4.png)

## Move

Same behavior, no errors.

MATT 10.9
Foundry 10.291

**Comment by Haxxer** [comment] 2022-12-28 09:15
This is baked into Tagger itself - there's no concept of "latest tag". If that is a feature you want to have, best request that on the Tagger repository.

**Comment by Shuggaloaf** [comment] 2022-12-28 20:27
I believe the issue is not that we want a "latest tag", but that Alter is only working for 1 instance of the tag. (Or at least it's the reason why I added a thumbs up)

Example if I have 5 walls all tagged as `WallsTagged` and I click a trigger to make any walls with that tag change from standard to invisible, then it only affects 1 instance and not all 5 as is the expected behavior.

**Comment by Shuggaloaf** [comment] 2022-12-28 21:12
Maybe a GIF would help better explain the issue. 

The top, red d20 tile trigger is set to Alter the tags `testWalls` to toggle between blocking light and allowing it. All 4 walls around the red light are tagged as testWalls. Expected behavior would be that all walls toggle. As you can see only the top wall around the red light toggles off and we get the console error, same as OP.

The lower, green d20 tile trigger is set to Alter each wall by ID (i.e. not using Tags) to toggle between blocking light and allowing it.  As you can see this works as expected. When clicked it allows the green light to shine through the walls. When clicked again, it blocks it. Also, no console error. 

Hopefully this can help narrow down what the actual issue is.

![Capture-02(1)](https://user-images.githubusercontent.com/79543184/209872433-98303c98-6ecf-4e6e-85b5-775899903446.gif)

**Comment by Haxxer** [comment] 2022-12-28 21:12
> I believe the issue is not that we want a "latest tag", but that Alter is only working for 1 instance of the tag. (Or at least it's the reason why I added a thumbs up)
> 
> Example if I have 5 walls all tagged as `WallsTagged` and I click a trigger to make any walls with that tag change from standard to invisible, then it only affects 1 instance and not all 5 as is the expected behavior.
> 
> edit: I also get the same console error message when it happens

Ah my bad, I misunderstood!

**Comment by Shuggaloaf** [comment] 2022-12-28 21:13
> Ah my bad, I misunderstood!

No worries, just making sure we're all on the same page. :)  Added another GIF above, maybe that will help shed some more light on this.

**Comment by ironmonk88** [comment] 2022-12-29 01:16
Not an issue with Tagger.  There's a fault in the Alter code.
Will be fixed for the next release.

**Comment by ironmonk88** [comment] 2023-01-11 04:33
Fixed in the latest release.

**Closed by ironmonk88** 2023-01-11 04:33 UTC
Labels: fixed waiting release
