### ISSUE TITLE
Rename the dialog buttons

### ISSUE THREAD

**Issue by DCFizban** [ironmonk88/monks-active-tiles#367] opened 2022-11-15 20:16 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be awesome if you could rename the yes/no buttons on the trigger dialog to anything you wanted, for example do you take the red or the blue pill? So yes would be renamed to red and the no button renamed to blue. Tnis could open up a whole new area for options.

**Additional context**

**Comment by ironmonk88** [comment] 2022-11-19 19:42
Please don't put the whole feature request in the title.

**Comment by ironmonk88** [comment] 2022-12-20 00:30
Closing as it's a duplicate of #147 
Just tidying up and realized it was a duplicate.

**Closed by ironmonk88** 2022-12-20 00:30 UTC
Labels: duplicate, enhancement
