### ISSUE TITLE
Add inbuilt filter to StopTokenMovement

### ISSUE THREAD

**Issue by MunchoTheCow** [ironmonk88/monks-active-tiles#596] opened 2023-09-11 11:44 UTC
Please add a variable filter check built into StopTokenMovement.
For example: to set it so a token with flying speed > 0 does not trigger a active tile (like a pit trap).

The proposed work around of Move token with original destination is undesirable, as it leaves a 1-2 second stop delay, making it very clear that "something" is there to the players.
Alternatively, the check could be added on the setup itself, since StopTokenMovement is always called due to limitations, it would effect to the same thing.

This change wouldn't cover every side case, but it would fix most of the issues related to tokens triggering tiles they shouldnt.

**Comment by ironmonk88** [comment] 2023-10-28 05:59
duplicate of #370 
As explained in that ticket, there's nothing I can do about it.

> It's not possible with the way Foundry works. MATT needs to stop regardless because by the time it knows it needs to stop, it would be too late to actually stop the token.

The change would end up introducing *way* more issues than it actually fixed.

Essentially I tried to do what you suggest but some actions take time and it sometimes resulted in the token having to reverse direction to go back to where it was supposed to have stopped.  And that was way worse than a small delay.  In the mean time It might have triggered other Tiles that it wasn't supposed to and reversing those would be next to impossible.  It's the best solution I had, as a 1-2 second delay can easily be passed off as just a glitch in movement when compared to some of the other issues that result in not stopping the token.

**Closed by ironmonk88** 2023-10-28 05:59 UTC
Labels: duplicate, enhancement, wontfix

**Comment by MunchoTheCow** [comment] 2023-10-30 14:18
I added a simple filter to my local version on the trigger of the actual tile itself, mainly to fix issues with flying creatures triggering pressure tiles, and that works perfectly for the issues I was having, since the check is done on trigger (not during the action processing), you get no issues or bugs, but admittingly it's not as powerful as a mid action filter, but as you said that seems unfixable due to foundry itself.
