### ISSUE TITLE
[BUG] Chat Message Error

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#486] opened 2023-05-06 16:55 UTC
I have no idea why here, but for some reason some tokens are resulting in these errors when triggering a Chat Message.

https://user-images.githubusercontent.com/99844555/236637048-aeeaf6f7-db92-4a01-9896-3d40d043843e.mp4

![image](https://user-images.githubusercontent.com/99844555/236637141-f5af1c32-811b-41f9-a311-97c899beae17.png)
![image](https://user-images.githubusercontent.com/99844555/236637161-3dc4f3b5-f972-4427-a34a-5e1019c8c2ed.png)

MATT 10.15
PF2 4.11.2

**Comment by ironmonk88** [comment] 2023-05-06 17:47
Just so I don't forget...
This is caused by a token that has the ownership set to everyone.  `default` is an owner and isn't, obviously, a player id.

**Comment by ironmonk88** [comment] 2023-05-13 03:40
Should be fixed in the latest release.

**Closed by ironmonk88** 2023-05-13 03:40 UTC
Labels: fixed waiting release
