### ISSUE TITLE
[BUG] Teleporting Duplicates Token

### ISSUE THREAD

**Issue by Quasxen** [ironmonk88/monks-active-tiles#742] opened 2024-04-06 15:58 UTC
**Describe the bug**
I have a couple scenes I want to have linked through a "teleporter". When I move a token into the tile it does get teleported and the scene changes. However, there are 2 copies of the token and either one or both of them are no longer moveable

**To Reproduce**
I just have token move in to the tile

**Expected behavior**
I would expect the token to be teleported, only the single instance of the token to exist, token to be controlled still, and the scene to change

**Screenshots**
![Actions](https://github.com/ironmonk88/monks-active-tiles/assets/166070156/02dc321f-187b-486f-8211-fe69dffaa9b5)
![Scene_Change](https://github.com/ironmonk88/monks-active-tiles/assets/166070156/f55a032a-4dec-4008-b9b1-2253350f6932)
![Teleport_Detail](https://github.com/ironmonk88/monks-active-tiles/assets/166070156/d07ccea4-6aa8-4443-b9b3-6912508c63c2)

**Please complete as much of the following information as possible:**
Running Locally
 - Foundry Version 11.315
 - System D&D5e 3.1.1
 - Module version 11.23
 - Are there any errors in the console - log file attached showing errors. I cleared it and then moved the token into the tile
 - [Teleport_Log.txt](https://github.com/ironmonk88/monks-active-tiles/files/14894084/Teleport_Log.txt)

**Comment by ironmonk88** [comment] 2024-04-07 00:32
It's working correctly for me.
Have you run Find the Culprit to see if it's another module running interference?
You also shouldn't need the "Change Scene" action.  Teleport already changes scenes for players.

**Comment by Quasxen** [comment] 2024-04-07 02:34
Not sure Find the Culprit is going to help:

1 Module Active - Monk's Active Tile Triggers
![image](https://github.com/ironmonk88/monks-active-tiles/assets/166070156/87882f29-596d-4385-bd61-9e81825c611b)


Still get the duplicating token with Teleport:
![image](https://github.com/ironmonk88/monks-active-tiles/assets/166070156/0b60936e-8b84-43bb-9f2f-2e7c4f20c726)


Settings for the Tile:
![image](https://github.com/ironmonk88/monks-active-tiles/assets/166070156/1e6a7232-f47f-4a13-ba83-0e21501e99fb)


Unchecked the Delete Token and Preserve Values setting:
![image](https://github.com/ironmonk88/monks-active-tiles/assets/166070156/04496077-3e79-4204-93f8-9ddb0221b06f)

**Comment by Quasxen** [comment] 2024-04-07 02:55
Okay, now I'm even more confused. I had the latest version of the module. I uninstalled it and then re-installed it using the manifest path. Everything seems to be working perfectly now, even with all the other modules turned back on.

Sorry about the time, I should've tried this before submitting a bug

**Comment by Crowguard** [comment] 2024-04-07 03:25
That isn't a bug; its working as intended. You have it teleporting once on Enter, and again on Stop Within Tile. 

Pick one or the other, there isn't any reason to use both triggers there.

**Comment by ironmonk88** [comment] 2024-04-07 04:43
Closing this as Crowguard is correct, you're triggering it twice, so it's going to teleport twice.
Working as intended.

**Closed by ironmonk88** 2024-04-07 04:43 UTC
Labels: working as expected
