### ISSUE TITLE
Adding Actions Trouble

### ISSUE THREAD

**Issue by applefixture** [ironmonk88/monks-active-tiles#146] opened 2022-03-18 22:25 UTC
Hi there! I am setting up a game in a pathfinder 2e foundry world and I am experiencing a problem with adding actions. When I had played a few weeks ago, the mod did not have this issue but downgrading the mod does not fix it either. 

When I set up my tile and head to the triggers tab I cannot add an action. No new window pops up and no message comes up either. It just doesn't work. I tested the mod in a dnd 5e world and it works no problem so it seems to be a pathfinder 2e problem. I haven't had this issue pop up before and I am not sure what to do from here. Any advice would be much appreciated!

**Comment by ironmonk88** [comment] 2022-03-18 23:09
Yeah.  Looks like PF2E changed something in the way their system works.
It's fixed, just waiting for release.
Technically this is a duplicate of #143.

**Comment by applefixture** [comment] 2022-03-18 23:11
Ah! I missed that issue number, but thank you! Excited to see it working again!

**Comment by ironmonk88** [comment] 2022-12-20 00:31
Closing as I believe it should be working now.

**Closed by ironmonk88** 2022-12-20 00:31 UTC
