### ISSUE TITLE
[BUG] Play Sound for Label

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#664] opened 2023-12-09 07:39 UTC
Label is not updating in the actions list to match the dropdown. Seems to be visual only.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/39f8af4d-4de9-48a2-9283-4ca2c52dd350)

MATT 11.17
Foundry 11.315

**Comment by mfozz** [comment] 2023-12-17 21:44
I'm having the same issue. Stop Sound also stopped working for my tagged tiles, but I'm not sure whether the issue is related (might submit a bug after testing).

**Comment by ironmonk88** [comment] 2023-12-25 20:50
Fixed the labelling issue, but if the stopped sound action has stopped working for tagged tiles, please submit a new ticket.

**Comment by ironmonk88** [comment] 2023-12-27 23:20
Fixed in the recent release.

**Closed by ironmonk88** 2023-12-27 23:20 UTC
Labels: fixed waiting release
