### ISSUE TITLE
Multiple separate conditions-and-actions for a single tile

### ISSUE THREAD

**Issue by wickermoon** [ironmonk88/monks-active-tiles#278] opened 2022-09-01 04:19 UTC
**Is your feature request related to a problem? Please describe.**
I want to create a button whose background changes when the mouse pointer hovers over it and which opens a journal entry, when you click on it. I use a tile plus MATT, but MATT only allows me to either trigger onClick or onHover, but not on both. I would have to create a second, invisible tile to create this effect. :/

**Describe the solution you'd like**
I would like to define actions for several triggers. Let me add a trigger to a tile the same way I add actions to a trigger.

**Comment by Crowguard** [comment] 2022-09-01 16:44
Duplicate of #210 and #132.

**Comment by ironmonk88** [comment] 2022-12-19 22:37
Closing because it's a duplicate and already implemented.

**Closed by ironmonk88** 2022-12-19 22:37 UTC
Labels: enhancement
