### ISSUE TITLE
Reset and stop commands?

### ISSUE THREAD

**Issue by Sinfulglare** [ironmonk88/monks-active-tiles#273] opened 2022-08-28 07:54 UTC
I just started using this mod and its amazing to say the least, but I was trying to figure out how to do something specific and I don't know if its just not a feature or I just don't know how to set it up.

so the puzzle I was trying to set up is basic you click the switch it starts a timer and after 30 seconds the door unlocks nothing bad happens. Well the timer portion is supposed to create panic and get the party to click the switch again resetting it. Now when I tried this the previous instance of commands kept running and I couldn't figure how to get a if activated stop previous commands function in or just stop previous and reset? Is this some that's currently possible and I'm just stupid or is it something that can be added?

**Comment by ironmonk88** [comment] 2022-10-30 06:47
The problem is that delayed actions escaped the "Stop Remaining Actions" action.
I've fixed it so running the command will cancel any delayed tasks now.

**Comment by ironmonk88** [comment] 2022-11-09 17:32
Fixed in latest release.

**Closed by ironmonk88** 2022-11-09 17:32 UTC
Labels: enhancement, fixed waiting release
