### ISSUE TITLE
[BUG] v10 exclude transparent box

### ISSUE THREAD

**Issue by WizardForHire123** [ironmonk88/monks-active-tiles#293] opened 2022-09-03 15:53 UTC
**Describe the bug**
see discord thread here 
https://discord.com/channels/862414864692281386/862421211749154816/1015634575529091102

**Expected behavior**
no error transparent box should be excluded in the tile image. guessing related to v10 canvas changes

**Screenshots**

**Please complete as much of the following information as possible:**
 - unsure what person was using
 -tested in foundry v10
 - 5e and botd
 - current v10 as of 9/3/22
 - see thread link
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.

**Additional context**
not my issue my environment for v10 is having issue migrating from forge. I'll test eventually and comment with my own research after.

**Comment by Crowguard** [comment] 2022-09-03 15:59
![image](https://user-images.githubusercontent.com/99844555/188278336-9d32b0e5-a2ad-4f0d-8f3e-67c6f53608e7.png)

After turning this setting on for a tile, attempting to load the scene the tile is on results in this.

**Comment by Crowguard** [comment] 2022-09-03 16:07
![image](https://user-images.githubusercontent.com/99844555/188278903-5b9cc458-ed77-4349-9cf8-64de7f9d2a34.png)
Error that occurs the first time another scene is activated while on a locked one.

**Comment by d34d-p1x3l** [comment] 2022-09-03 18:03
![Error message 1](https://user-images.githubusercontent.com/82676239/188278122-00ca64c7-2703-4146-a98e-df6c012a483b.png)
Some scenes won't load with Active Tiles and v10. They did previously in v9.
![Error message 2](https://user-images.githubusercontent.com/82676239/188278148-832d4ee6-3623-4ed2-86ed-944d27e2de09.png)
The culprit seems to be Tiles with alpha maps that I select "Exclude transparent area when triggering". It calls a function called _createAlphaMap that Foundry is now saying isn't there. I did try to find out if the function had been deprecated or renamed, but after being bounced around the Foundry Discord from channel to channel, eventually I got told that it was not for me to sort out and that the dev in question needs to sort it themselves. 

It seems easy enough to reproduce though. Create a new test scene. Create a new tile on that scene. Go to the Active Tiles "Trigger" tab and select "Exclude transparent area when triggering". Move away from the scene and then back again. Foundry will not render the canvas.
You can't disable the option as the tiles are not there to see, and turning off the module obviously removes the option.

Thanks to WizardForHire123 and Crowguard for all their help today.

Tested on 5e and Blades in the Dark systems.

**Comment by ironmonk88** [comment] 2022-09-17 19:04
This should be fixed now.

**Closed by ironmonk88** 2022-09-17 19:04 UTC
Labels: fixed waiting release
