### ISSUE TITLE
[BUG] Minor Error on Module Update in V11

### ISSUE THREAD

**Issue by Truncated** [ironmonk88/monks-active-tiles#811] opened 2024-07-06 04:11 UTC
**Describe the bug**
When updating modules in setup, I get this error:
Error: Module validation errors: documentTypes: is not a valid sub-types configuration: 'RegionBehavior' is not a valid Document type

**To Reproduce**
Update the module

**Expected behavior**
Not get an error. :)

**Screenshots**
![image](https://github.com/ironmonk88/monks-active-tiles/assets/14208325/f24bb2bd-ec93-46bb-be2c-23a4388929a3)

**Please complete as much of the following information as possible:**
 - Browser [e.g. chrome, safari] : Edge
 - Foundry Version [e.g. v9] : v11.315
 - System [e.g. D&D5e, Pathfinder 2e]:  N/A
 - Module version:  11.27
 - Are there any errors in the console [e.g. press F12 and look for red text]:  Yes:
![image](https://github.com/ironmonk88/monks-active-tiles/assets/14208325/a122de31-84a2-4263-bdc1-e4bad24d569f)

 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.:  N/A

**Additional context**

**Comment by ironmonk88** [comment] 2024-07-06 23:16
![image](https://github.com/ironmonk88/monks-active-tiles/assets/75920956/54338fa8-d3b7-42bf-9f4d-b622f54041f2)

closing as duplicate of #792 and there is already a posted notification on the main page.

**Closed by ironmonk88** 2024-07-06 23:16 UTC
Labels: duplicate
