### ISSUE TITLE
[BUG] Tiles not triggering with Levels mod active

### ISSUE THREAD

**Issue by Co0nmz** [ironmonk88/monks-active-tiles#285] opened 2022-09-01 19:50 UTC
**Description:**
With no mods active, MATT works fine.
With the Levels mod (and its dependencies) active, 

I recieve this error and all active tiles dont trigger anymore:

monks-active-tiles.js:3181 Uncaught (in promise) ReferenceError: _levels is not defined
[Detected 1 package: monks-active-tiles]
    at Object.fn (monks-active-tiles.js:3181:59)
    at #call (foundry.js:688:20)
    at Hooks.call (foundry.js:670:38)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:12594:47)
    at async ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:12507:22)
    at async TokenDocumentPF.updateDocuments (commons.js:5652:23)

**To Reproduce**
1. Install MATT and Levels
2. try triggering a tile (I tested only on Enter triggers)

 - Foundry Version 10
 - System Pathfinder 1e
 - Module version latest

**Comment by Crowguard** [comment] 2022-09-01 23:10
Duplicate of #279 Monk.

**Closed** 2022-09-13 04:19 UTC
Labels: duplicate
