### ISSUE TITLE
[BUG] Can't rearrange Actions on new tiles until the actions are saved and closed down.

### ISSUE THREAD

**Issue by Gurrgel** [ironmonk88/monks-active-tiles#249] opened 2022-07-15 21:28 UTC
**Describe the bug**
If I go into the Triggers tab for a tile, that doesn't already have any MATT actions, and then add actions to said tile, I'm unable to rearrange the order of said actions until I've pressed the "Update Tile" button, which is a bit annoying since the whole tile configuration then has to be reopened again. Once I've updated the tile and reopened it, it things behave as they should.

**To Reproduce**
Steps to reproduce the behavior (has worked every time for me :
1. Open up a tile that doesn't already have any Actions set up from MATT, either an entirely new tile dropped onto a scene, or an older tile that just hasn't been used for MATT yet.
2. Add 2-3 actions (tested with combinations of the "Landing" and the "Activate/Deactivate" actions)
3. Try to move any of the actions to another spot on the list.

**Expected behavior**
I would expect the action to be moved to its new spot seeing as they can usually be dragged to anywhere you'd like in the list, at least after I update the tile.

**Screenshots**
The following error message is given to me in the console when I try to move an action around (before having saved the tile and reopened it).
![image](https://user-images.githubusercontent.com/99760890/179312693-998844d6-b7cf-447c-879b-bf5c5ffd3a0b.png)

**Please complete as much of the following information as possible:**
 - Chrome or the Foundry application.
 - Foundry Version: v9.269
 - System: D&D 5e 1.6.3
 - Module version: 1.0.90, although I've had it for at least the two previous versions as well.
 - See image above for the error I get from the console.
 - I'm getting this issue both with a lot of modules active, and if I use Find the Culprit to turn everything but MATT off.

**Comment by Mecheye** [comment] 2022-07-23 13:05
+1 for this. Its not that much of an inconvenience but it is still unintended behavior

**Comment by ironmonk88** [comment] 2022-12-19 22:57
Closing this as it should have been fixed.

**Closed by ironmonk88** 2022-12-19 22:57 UTC
