### ISSUE TITLE
Feature request: suppress Request Roll sound for automatic blind GM rolls

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk88/monks-active-tiles#72] opened 2021-11-24 03:14 UTC
For certain blind GM rolls (e.g. Perception check, Wisdom saving throw), it's not always desirable for a player to know that the roll is occurring. But the Request Roll sound gives it away to the player even when the roll is set to automatic. It would be great to have an option in the Request Roll action to suppress the Roll Request sound from Monk's TokenBar.

**Comment by ironmonk88** [comment] 2021-12-28 21:23
I think this is working as intended.  Blind GM rolls are still rolls the players are aware of, they just can't see the results.
If you want them to be completely hidden, then you'd use Self Roll.  And Self Roll shouldn't emit a sound to the players.

**Comment by ironmonk88** [comment] 2022-12-20 01:52
Closing as I believe it was a miscommunication on how Blind Rolls work.

**Closed by ironmonk88** 2022-12-20 01:52 UTC
